# You can now use powerful pattern-based exclusions in your exclusions.yaml:
# contains: Alle will exclude any row/column containing "Alle"
# startswith: rel. 100 will exclude any row/column starting with "rel. 100"
# endswith: wert would exclude any row/column ending with "wert"

exclude_columns:
  - contains: Mittelwert
  - startswith: Alle
  - startswith: Ertrag
  - startswith: Differen

exclude_rows:
  - startswith: rel
  - startswith: vgl reduziert
  - startswith: Alle
  - endswith: alle
  - endswith: Latitude XL
  - endswith: WDurum
  - startswith: Differenz
  - startswith: GD(LSD)
  - startswith: VD
  - startswith: Sorte
  - startswith: Mittel VRS